### ISSUE TITLE
Removing `doSexRatio()` now but do we care about "both" in output, i.e., males and females

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pfmc-assessments/PacFIN.Utilities#133]
**Is your feature request related to a problem? Please describe.**
I am removing `doSexRatio()` from PacFIN.Utilities, something that we talked about doing after last cycle. But, I am curious if people are interested in keeping the "both" output, where right now we have "females", "males", "unsexed", and "both". Both is the composition data for males and females joined together, so "sexed" fish. This seems really complicated, why would you want to have the compositions for sexed fish separate from unsexed fish? I mean you could still get them even if we remove the "both" functionality by just subsetting the input data frame for sexed fish and then marking them all as unsexed.

**Describe the solution you'd like**
Nuke the "both" functionality from the code base.

**Describe alternatives you've considered**
Keep the code as is but continue to remove `doSexRatio()`.

**Additional context**

**Comment by chantelwetzel-noaa** [comment]
IMO, the "both" option is the more useful version in the `writeComps()` since it formats the data in the expected SS3 format for a two-sex model.  If you are looking to simplify the code, which I support, I would opt to delete the separate "female" and "male" or the "both" if you add the functionality to format the separate sex composition data for a two-sex model.

**Comment by kellijohnson-NOAA** [comment]
I don't see the data from "both" actually being written to any file. I think we are talking about two different things, sorry that I wasn't clear in the original comment. In `getComps()` the column "both" stores combined information about males and females. It is literally the sum of the female weight plus the sum of the male weight. In writeComps() the output contains "FemalesThenMales" (uses female and male column), "FemalesOnly" (uses female column), "MalesOnly" (uses male column), and "UnsexedOnly" (uses unsexed column) without printing any information from the "both" column of the input data frame. Here is the head of the input data frame that goes into writeComps()
```
> head(comps_len)
  fleet fishyr season lengthcm   female fsamps ftows     male msamps mtows
1     2   1986      1       70 148.2118      1     3   0.0000      0     0
2     2   1986      1       46 148.2118      1     3 148.2118      1     3
3     2   1986      1       63 651.7612      2     3 831.6299      2     3
4     2   1986      1       54 503.5494      1     3 503.5494      1     3
5     2   1986      1       60 503.5494      1     3 919.3644      2     3
6     2   1986      1       65 148.2118      1     3 415.8150      1     3
    unsexed usamps utows ONLY_U_TOWS alltows      both bsamps btows
1  635.3178      1     5           5       8  148.2118      1     3
2    0.0000      0     0           0       8  296.4235      2     3
3  940.3596      2     5           5       8 1483.3911      4     3
4 4141.9189      3     5           5       8 1007.0988      2     3
5 8879.4173      6     5           5       8 1422.9138      3     3
6 5099.2854      5     5           5       8  564.0267      2     3
```

**Comment by chantelwetzel-noaa** [comment]
Thank you for the clarification.  I added the "b" columns in order to calculate the appropriate samples sizes when someone is doing a two-sex model. I recall that simply adding the `ftows` + `mtows` resulted in the number of unique tows (or rather trips) was incorrect. For example, a sampled tow/trip that had both sexes samples would result in a value of 2 tow/trips vs. the correct answer of 1 tow/trip.

**Comment by kellijohnson-NOAA** [comment]
Thanks @chantelwetzel-noaa this makes sense now!
